[graph]
targets = [
  { triple = "x86_64-pc-windows-msvc" },
  { triple = "x86_64-apple-darwin" },
  { triple = "aarch64-apple-darwin" },
]
all-features = true

[advisories]
version = 2
yanked = "deny"
unmaintained = "workspace"
ignore = []

[licenses]
version = 2
confidence-threshold = 0.93
allow = [
  "0BSD",
  "Apache-2.0",
  "BSD-2-Clause",
  "BSD-3-Clause",
  "BSL-1.0",
  "CC0-1.0",
  "ISC",
  "MIT",
  "MIT-0",
  "Unicode-3.0",
  "Unlicense",
  "Zlib",
]
exceptions = [
  { allow = ["MPL-2.0"], crate = "cssparser@0.36.0" },
  { allow = ["MPL-2.0"], crate = "cssparser-macros@0.6.1" },
  { allow = ["MPL-2.0"], crate = "dtoa-short@0.3.5" },
  { allow = ["MPL-2.0"], crate = "option-ext@0.2.0" },
  { allow = ["MPL-2.0"], crate = "selectors@0.36.1" },
]
private = { ignore = true }

[bans]
multiple-versions = "warn"
wildcards = "deny"
highlight = "all"
deny = []
skip = []
skip-tree = []

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []
