// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ErrorCode } from './ErrorCode';

export type AppError = {
  code: ErrorCode;
  message: string;
  details: { [key in string]: string };
  retryable: boolean;
  operationId: string | null;
};
