// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClassificationRuleAction } from './ClassificationRuleAction';
import type { ClassificationRuleMatcherKind } from './ClassificationRuleMatcherKind';

export type ClassificationRuleInput = {
  matcherKind: ClassificationRuleMatcherKind;
  pattern: string;
  action: ClassificationRuleAction;
  priority: number;
  enabled: boolean;
};
