// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClassificationRuleInput } from './ClassificationRuleInput';

export type ClassificationRuleSummary = {
  id: string;
  input: ClassificationRuleInput;
  createdAt: string;
  updatedAt: string;
};
