// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ClassificationRuleAction =
  | { kind: 'include' }
  | { kind: 'exclude' }
  | { kind: 'assignProject'; projectId: string };
