// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClassificationCategory } from './ClassificationCategory';
import type { ClassificationReason } from './ClassificationReason';
import type { UserClassificationOverride } from './UserClassificationOverride';

export type ClassificationResult = {
  score: number;
  version: number;
  category: ClassificationCategory;
  reasons: Array<ClassificationReason>;
  userOverride: UserClassificationOverride | null;
  isDevelopment: boolean;
};
