// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Confirms the exact profile identity removed by the Supervisor. Credential
 * references and write-only secret values are intentionally absent.
 */
export type DeleteLaunchProfileResponse = { profileId: string };
