// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LaunchExecution } from './LaunchExecution';

/**
 * A detector may propose execution, but this DTO is not a persistable launch
 * mode. The lifecycle boundary must validate and explicitly accept it first.
 */
export type DetectedScriptSuggestion = {
  detectorId: string;
  sourcePath: string;
  suggestedExecution: LaunchExecution;
};
