// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiagnosticContentKind } from './DiagnosticContentKind';
import type { DiagnosticContentPrivacy } from './DiagnosticContentPrivacy';

/**
 * One bounded entry in the diagnostic content checklist. `included` is the
 * default selection in a manifest preview and the actual selection in an
 * export result.
 */
export type DiagnosticManifestItem = {
  kind: DiagnosticContentKind;
  included: boolean;
  available: boolean;
  estimatedBytes: number;
  maximumBytes: number;
  privacy: DiagnosticContentPrivacy;
  truncated: boolean;
};
