// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The content-level privacy boundary applied before an item can be exported.
 */
export type DiagnosticContentPrivacy = 'metadataOnly' | 'structuredRedacted' | 'aggregateOnly';
