// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Closed diagnostic content categories. Managed-process stdout/stderr,
 * commands, environment values, credential references, paths, and session
 * tokens have no representable category in this contract.
 */
export type DiagnosticContentKind = 'systemSummary' | 'applicationLogs' | 'databaseSummary';
