// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Persistable execution modes. Detected scripts are suggestions and must be
 * accepted into one of these concrete modes before a profile can be saved.
 */
export type DirectLaunch = { executable: string; argv: Array<string> };
