// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EnvironmentLayer } from './EnvironmentLayer';
import type { EnvironmentPreviewValue } from './EnvironmentPreviewValue';

export type EnvironmentPreviewEntry = {
  name: string;
  value: EnvironmentPreviewValue;
  source: EnvironmentLayer;
};
