// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ErrorCode =
  | 'INVALID_ARGUMENT'
  | 'NOT_FOUND'
  | 'ALREADY_EXITED'
  | 'ACCESS_DENIED'
  | 'IDENTITY_MISMATCH'
  | 'NOT_SUPPORTED'
  | 'SUPERVISOR_UNAVAILABLE'
  | 'TIMEOUT'
  | 'CONFLICT'
  | 'STORAGE_ERROR'
  | 'PLATFORM_ERROR'
  | 'INTERNAL';
