// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExecutableCandidateSource } from './ExecutableCandidateSource';

export type ExecutableCandidate = { path: string; source: ExecutableCandidateSource };
