// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LaunchProfileInput } from './LaunchProfileInput';

/**
 * The client supplies only the profile being previewed. Platform and lower
 * environment layers come from a non-serializable Supervisor context.
 */
export type ExecutionPreviewRequest = { profile: LaunchProfileInput };
