// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DirectExecutionPreview } from './DirectExecutionPreview';
import type { ShellExecutionPreview } from './ShellExecutionPreview';

export type ExecutionInvocationPreview =
  | ({ mode: 'direct' } & DirectExecutionPreview)
  | ({ mode: 'shell' } & ShellExecutionPreview);
