// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PathExecutableCandidateSource } from './PathExecutableCandidateSource';

export type ExecutableCandidateSource =
  | 'explicit'
  | 'workingDirectory'
  | { path: PathExecutableCandidateSource };
