// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NotFoundExecutableResolution } from './NotFoundExecutableResolution';
import type { NotSupportedExecutableResolution } from './NotSupportedExecutableResolution';
import type { UnknownExecutableResolution } from './UnknownExecutableResolution';

export type ExecutableResolution =
  | ({ status: 'unknown' } & UnknownExecutableResolution)
  | ({ status: 'notFound' } & NotFoundExecutableResolution)
  | ({ status: 'notSupported' } & NotSupportedExecutableResolution);
