// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExitRunImpact } from './ExitRunImpact';

/**
 * `assessment_id` binds the exact sorted union of live controls and durable
 * unfinished runs to one Supervisor incarnation, preventing stale exit
 * confirmation after state changes or an ABA-shaped restart.
 */
export type ExitImpactSummary = { assessmentId: string; runs: Array<ExitRunImpact> };
