// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExitRetainedReason } from './ExitRetainedReason';

/**
 * One bounded, content-free exit consequence. Commands, environment values,
 * paths, process identities, and profile snapshots never cross this boundary.
 */
export type ExitRunImpact =
  | { kind: 'launching'; runId: string }
  | { kind: 'running'; runId: string }
  | { kind: 'gracefulStopping'; runId: string; operationId: string }
  | { kind: 'gracefulTimedOut'; runId: string; operationId: string }
  | { kind: 'forceStopping'; runId: string; operationId: string }
  | { kind: 'retained'; runId: string; reason: ExitRetainedReason };
