// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GetDiagnosticsManifestResponse } from './GetDiagnosticsManifestResponse';

/**
 * Result of atomically publishing one diagnostic JSON document under the
 * Supervisor-owned export root. Only a generated file name crosses the wire;
 * an absolute filesystem path never does.
 */
export type ExportDiagnosticsResult = {
  fileName: string;
  totalBytes: number;
  sha256: string;
  manifest: GetDiagnosticsManifestResponse;
};
