// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The system summary is mandatory. Application logs are the structured,
 * bounded application ring only; managed-process output is never eligible.
 */
export type ExportDiagnosticsRequest = {
  includeApplicationLogs: boolean;
  includeDatabaseSummary: boolean;
};
