// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A delivered stop signal does not prove that an external process exited.
 */
export type ExternalProcessStopOutcome = 'signalDelivered';
