// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The only supported scope for stopping a process that was discovered but
 * was not launched through a Supervisor-owned control boundary.
 */
export type ExternalProcessStopScope = 'singleProcess';
