// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EnvironmentPreviewEntry } from './EnvironmentPreviewEntry';
import type { ExecutableResolution } from './ExecutableResolution';
import type { ExecutionInvocationPreview } from './ExecutionInvocationPreview';
import type { ExecutionPlatform } from './ExecutionPlatform';
import type { PathExtensionResolution } from './PathExtensionResolution';
import type { PathResolution } from './PathResolution';

export type FinalExecutionPreview = {
  platform: ExecutionPlatform;
  workingDirectory: string;
  interactive: boolean;
  requiresCredentialResolution: boolean;
  invocation: ExecutionInvocationPreview;
  environment: Array<EnvironmentPreviewEntry>;
  path: PathResolution;
  pathExtensions: PathExtensionResolution;
  executableResolution: ExecutableResolution;
};
