// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Requests a force stop through the control boundary established at launch.
 * An active graceful operation may be replaced only when its exact ID is
 * named, preventing a stale confirmation from superseding newer work.
 */
export type ForceStopManagedRunRequest = { runId: string; supersedeOperationId: string | null };
