// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiagnosticManifestItem } from './DiagnosticManifestItem';

/**
 * Bounded checklist shown before export and embedded in the final result.
 */
export type GetDiagnosticsManifestResponse = {
  formatVersion: number;
  items: Array<DiagnosticManifestItem>;
  selectedEstimatedBytes: number;
  selectedMaximumBytes: number;
  byteBudget: number;
};
