// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Empty read request for the authoritative consequences of exiting the UI.
 * The Supervisor derives every affected run from durable state and its live
 * control table; the client cannot nominate or omit runs.
 */
export type GetExitImpactRequest = Record<symbol, never>;
