// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ManagedLogIoErrorKind } from './ManagedLogIoErrorKind';
import type { ManagedLogStream } from './ManagedLogStream';
import type { ManagedLogTextStatus } from './ManagedLogTextStatus';

/**
 * Bounded plain-text range plus the stream position observed atomically with
 * the read. Log text must never be emitted through `Debug` or interpreted as
 * HTML.
 */
export type GetManagedLogRangeResponse = {
  runId: string;
  stream: ManagedLogStream;
  observedSequence: number;
  firstAvailableByteOffset: number;
  firstByteOffset: number;
  nextByteOffset: number;
  streamEndByteOffset: number;
  text: string;
  hasMore: boolean;
  complete: boolean;
  endOfFile: boolean;
  ioStatusKnown: boolean;
  diskError: ManagedLogIoErrorKind | null;
  readError: ManagedLogIoErrorKind | null;
  textStatus: ManagedLogTextStatus;
};
