// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ManagedLogStream } from './ManagedLogStream';

/**
 * Requests a bounded filtered UTF-8 byte range from one managed-run stream.
 * An omitted offset asks for the first currently retained scalar boundary.
 */
export type GetManagedLogRangeRequest = {
  runId: string;
  stream: ManagedLogStream;
  startingByteOffset: number | null;
  maximumBytes: number;
};
