// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProcessInstanceKey } from './ProcessInstanceKey';

/**
 * Resolves lifecycle control for one exact process instance. The complete
 * identity is required so a stale selection cannot resolve a reused PID.
 */
export type GetProcessDetailsRequest = { processInstanceKey: ProcessInstanceKey };
