// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProcessControl } from './ProcessControl';
import type { ProcessInstanceKey } from './ProcessInstanceKey';

export type GetProcessDetailsResponse = {
  processInstanceKey: ProcessInstanceKey;
  control: ProcessControl;
};
