// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GetSnapshotRequest = {
  startingRevision: number;
  /**
   * Opaque continuation returned by the preceding chunk. `None` always
   * starts a new, frozen snapshot session.
   */
  cursor: string | null;
};
