// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EnvironmentLayer } from './EnvironmentLayer';

export type KnownPathExtensionResolution = {
  value: string;
  extensions: Array<string>;
  source: EnvironmentLayer;
};
