// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CredentialReferenceLaunchEnvironmentValue } from './CredentialReferenceLaunchEnvironmentValue';
import type { PlainLaunchEnvironmentValue } from './PlainLaunchEnvironmentValue';

export type LaunchEnvironmentValue =
  | ({ kind: 'plain' } & PlainLaunchEnvironmentValue)
  | ({ kind: 'credentialReference' } & CredentialReferenceLaunchEnvironmentValue);
