// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LaunchEnvironmentEntry } from './LaunchEnvironmentEntry';
import type { LaunchExecution } from './LaunchExecution';

export type LaunchProfileInput = {
  projectId: string | null;
  name: string;
  execution: LaunchExecution;
  workingDirectory: string;
  environment: Array<LaunchEnvironmentEntry>;
  interactive: boolean;
  stopTimeoutMs: number;
};
