// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DirectLaunch } from './DirectLaunch';
import type { ShellLaunch } from './ShellLaunch';

export type LaunchExecution =
  | ({ mode: 'direct' } & DirectLaunch)
  | ({ mode: 'shell' } & ShellLaunch);
