// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ManagedRunSummary } from './ManagedRunSummary';
import type { ManagedStopKind } from './ManagedStopKind';
import type { ManagedStopOutcome } from './ManagedStopOutcome';
import type { ManagedStopSignalDisposition } from './ManagedStopSignalDisposition';
import type { ManagedStopStatus } from './ManagedStopStatus';

/**
 * Public projection of a durable operation and its current run state. Signal
 * and outcome values are closed enums; platform diagnostics never cross this
 * boundary.
 */
export type ManagedStopOperationResult = {
  operationId: string;
  run: ManagedRunSummary;
  kind: ManagedStopKind;
  status: ManagedStopStatus;
  signalDisposition: ManagedStopSignalDisposition | null;
  outcome: ManagedStopOutcome | null;
  createdAt: string;
  updatedAt: string;
  completedAt: string | null;
};
