// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Sanitized IO categories for managed log collection and delivery. These
 * values never contain a path, OS error message, or log body.
 */
export type ManagedLogIoErrorKind =
  | 'invalidConfiguration'
  | 'invalidPath'
  | 'notFound'
  | 'permissionDenied'
  | 'alreadyExists'
  | 'resourceBusy'
  | 'storageFull'
  | 'interrupted'
  | 'unexpectedEof'
  | 'invalidData'
  | 'limitExceeded'
  | 'writeZero'
  | 'unavailable'
  | 'otherIo';
