// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Resolved source encoding for one managed log stream. The stored/event text
 * is always normalized UTF-8 regardless of this source encoding.
 */
export type ManagedLogEncoding =
  | 'utf8'
  | 'utf16Le'
  | 'utf16Be'
  | { windowsCodePage: { codePage: number } };
