// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ManagedLogEncoding } from './ManagedLogEncoding';

/**
 * Encoding and sanitization evidence for one stream snapshot. Historical
 * readers return `Unknown` when no trusted status record is available.
 */
export type ManagedLogTextStatus =
  | {
      known: {
        encoding: ManagedLogEncoding;
        replacementUsed: boolean;
        controlsFiltered: boolean;
        fallbackUnavailable: boolean;
      };
    }
  | 'unknown';
