// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Independent output streams for an ordinary non-interactive managed run.
 */
export type ManagedLogStream = 'stdout' | 'stderr';
