// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProcessInstanceKey } from './ProcessInstanceKey';
import type { RunState } from './RunState';

/**
 * A bounded public projection of a Supervisor-owned managed run. The profile
 * timestamp identifies the immutable configuration revision used at launch.
 */
export type ManagedRunSummary = {
  runId: string;
  profileId: string;
  profileUpdatedAt: string;
  state: RunState;
  processInstanceKey: ProcessInstanceKey | null;
  /**
   * Controlled POSIX process group. Windows Job-managed runs leave this
   * empty because a console process-group identifier is not the Job owner.
   */
  processGroupId: number | null;
  startedAt: string;
  updatedAt: string;
  endedAt: string | null;
};
