// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ManagedLogChunk } from './ManagedLogChunk';

/**
 * One throttled UI event containing at most one chunk per output stream.
 */
export type ManagedLogBatch = { chunks: Array<ManagedLogChunk> };
