// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Durable progress of one idempotent stop operation. `Superseded` is a
 * terminal state used only when an explicitly linked force request replaces
 * a graceful operation.
 */
export type ManagedStopStatus =
  | 'requested'
  | 'signalPending'
  | 'inProgress'
  | 'timedOut'
  | 'completed'
  | 'superseded';
