// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ManagedLogIoErrorKind } from './ManagedLogIoErrorKind';
import type { ManagedLogStream } from './ManagedLogStream';
import type { ManagedLogTextStatus } from './ManagedLogTextStatus';

/**
 * One bounded, ordered plain-text update for a managed-run stream. Offsets
 * count bytes in the filtered UTF-8 representation and remain within
 * JavaScript's exact integer range. Log text must never be emitted through
 * `Debug` or interpreted as HTML.
 */
export type ManagedLogChunk = {
  runId: string;
  stream: ManagedLogStream;
  sequence: number;
  firstAvailableByteOffset: number;
  firstByteOffset: number;
  nextByteOffset: number;
  streamEndByteOffset: number;
  text: string;
  hasMore: boolean;
  caughtUp: boolean;
  endOfFile: boolean;
  ioStatusKnown: boolean;
  diskError: ManagedLogIoErrorKind | null;
  readError: ManagedLogIoErrorKind | null;
  deliveryError: ManagedLogIoErrorKind | null;
  textStatus: ManagedLogTextStatus;
};
