// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExecutableCandidate } from './ExecutableCandidate';
import type { ExecutableNotFoundReason } from './ExecutableNotFoundReason';

export type NotFoundExecutableResolution = {
  reason: ExecutableNotFoundReason;
  candidates: Array<ExecutableCandidate>;
};
