// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { KnownPathResolution } from './KnownPathResolution';
import type { UnknownPathResolution } from './UnknownPathResolution';

export type PathResolution =
  | ({ status: 'known' } & KnownPathResolution)
  | ({ status: 'unknown' } & UnknownPathResolution);
