// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { KnownPathExtensionResolution } from './KnownPathExtensionResolution';
import type { UnknownPathExtensionResolution } from './UnknownPathExtensionResolution';

export type PathExtensionResolution =
  | ({ status: 'known' } & KnownPathExtensionResolution)
  | ({ status: 'unknown' } & UnknownPathExtensionResolution)
  | { status: 'notApplicable' };
