// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EnvironmentLayer } from './EnvironmentLayer';
import type { PathEntryKind } from './PathEntryKind';

export type PathExecutableCandidateSource = {
  pathSource: EnvironmentLayer;
  pathIndex: number;
  entryKind: PathEntryKind;
};
