// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Environment values are mutually exclusive by construction. Empty plain
 * values are valid; credential references never contain the secret itself.
 */
export type PlainLaunchEnvironmentValue = { value: string };
