// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PortBinding } from './PortBinding';
import type { PortBindingKey } from './PortBindingKey';

export type PortDelta = { upserted: Array<PortBinding>; removed: Array<PortBindingKey> };
