// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AddressFamily } from './AddressFamily';
import type { PortProtocol } from './PortProtocol';
import type { ProcessInstanceKey } from './ProcessInstanceKey';

/**
 * Stable identity for a port binding. Observation metadata is deliberately
 * excluded so a binding can be removed after its mutable fields change.
 */
export type PortBindingKey = {
  protocol: PortProtocol;
  addressFamily: AddressFamily;
  localAddress: string;
  localPort: number;
  processInstanceKey: ProcessInstanceKey | null;
};
