// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AddressFamily } from './AddressFamily';
import type { FieldValue } from './FieldValue';
import type { PortOwnershipConfidence } from './PortOwnershipConfidence';
import type { PortProtocol } from './PortProtocol';
import type { PortState } from './PortState';
import type { ProcessInstanceKey } from './ProcessInstanceKey';

export type PortBinding = {
  protocol: PortProtocol;
  addressFamily: AddressFamily;
  localAddress: string;
  localPort: number;
  state: FieldValue<PortState>;
  processInstanceKey: ProcessInstanceKey | null;
  confidence: PortOwnershipConfidence;
  observedAt: string;
};
