// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ManagedRunSummary } from './ManagedRunSummary';
import type { ManagedStopOperationResult } from './ManagedStopOperationResult';

/**
 * Control evidence is mutually exclusive by construction. Managed details
 * carry the current durable run and, when present, its one active stop.
 */
export type ProcessControl =
  | { kind: 'external' }
  | { kind: 'managed'; run: ManagedRunSummary; activeStop: ManagedStopOperationResult | null };
