// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ProcessInstanceKey = {
  bootId: string;
  pid: number;
  /**
   * Decimal native creation-time representation. A string preserves the
   * full platform precision across JSON and JavaScript.
   */
  nativeStartTime: string;
};
