// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AccessLevel } from './AccessLevel';
import type { ClassificationResult } from './ClassificationResult';
import type { FieldValue } from './FieldValue';
import type { PortBinding } from './PortBinding';
import type { ProcessInstanceKey } from './ProcessInstanceKey';
import type { ProcessOwnership } from './ProcessOwnership';
import type { ProcessStatus } from './ProcessStatus';
import type { ProjectAssociationEvidence } from './ProjectAssociationEvidence';
import type { ProjectEvidence } from './ProjectEvidence';
import type { ProjectFeatureEvidence } from './ProjectFeatureEvidence';

export type ProcessRecord = {
  instanceKey: ProcessInstanceKey;
  parentInstanceKey: FieldValue<ProcessInstanceKey | null>;
  ownerUser: FieldValue<string>;
  executableName: FieldValue<string>;
  executablePath: FieldValue<string>;
  commandLine: FieldValue<string>;
  workingDirectory: FieldValue<string>;
  cpuPercent: FieldValue<number>;
  memoryBytes: FieldValue<number>;
  startedAt: FieldValue<string>;
  status: FieldValue<ProcessStatus>;
  accessLevel: AccessLevel;
  ownership: ProcessOwnership;
  /**
   * Present exactly when `ownership` is `Managed`. Native discovery never
   * sets this Supervisor-owned association.
   */
  managedRunId: string | null;
  projectAssociation: ProjectEvidence<ProjectAssociationEvidence>;
  projectFeatures: ProjectEvidence<Array<ProjectFeatureEvidence>>;
  /**
   * Compatibility field derived from project evidence or an explicit
   * AssignProject classification rule.
   */
  projectId: string | null;
  classification: ClassificationResult;
  /**
   * `Known(vec![])` means scanned with no bindings; other variants preserve
   * not-scanned, permission-limited, and unsupported states.
   */
  portBindings: FieldValue<Array<PortBinding>>;
  lastSeenRevision: number;
};
