// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Evidence produced by bounded project discovery.
 *
 * `Missing` means the relevant lookup completed and found no association,
 * while `Unknown` and the access variants mean no negative conclusion can be
 * drawn from the current observation.
 */
export type ProjectEvidence<T> =
  | { known: T }
  | 'missing'
  | 'unknown'
  | { accessLimited: { reason: string | null } }
  | 'notSupported';
