// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProcessInstanceKey } from './ProcessInstanceKey';

/**
 * Ephemeral UI demand for bounded process enrichment. The visible set is
 * validated by the Supervisor before any work is queued; a selected process
 * may also appear there and is then requested only at selected priority.
 */
export type RequestProcessEnrichmentRequest = {
  visibleProcessInstanceKeys: Array<ProcessInstanceKey>;
  selectedProcessInstanceKey: ProcessInstanceKey | null;
};
