// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Counts only process identities that the discovery scheduler accepted.
 * Missing identities are deliberately reported as not accepted rather than
 * failing the whole retryable, non-persistent request.
 */
export type RequestProcessEnrichmentResponse = {
  visibleAccepted: number;
  selectedAccepted: boolean;
};
