// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ManagedStopKind } from './ManagedStopKind';
import type { ProcessInstanceKey } from './ProcessInstanceKey';
import type { RunState } from './RunState';

/**
 * A deliberately content-free projection of one durable managed run. Profile
 * snapshots, commands, environment values, paths, exit summaries, and log
 * directories never cross this history boundary.
 */
export type RunHistoryItem = {
  runId: string;
  profileId: string;
  profileName: string;
  state: RunState;
  processInstanceKey: ProcessInstanceKey | null;
  stopKind: ManagedStopKind | null;
  recoveryState: RunState | null;
  startedAt: string;
  updatedAt: string;
  endedAt: string | null;
};
