// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RunState =
  | 'starting'
  | 'running'
  | 'stopRequested'
  | 'gracefulStopping'
  | 'forceStopping'
  | 'exited'
  | 'failed'
  | 'recovered'
  | 'exitedWhileOffline'
  | 'identityMismatch'
  | 'orphaned';
