// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CreateLaunchProfileRequest } from './CreateLaunchProfileRequest';
import type { UpdateLaunchProfileRequest } from './UpdateLaunchProfileRequest';

/**
 * Identity and timestamps on create remain Supervisor-owned. Updates name a
 * target separately and require its last observed timestamp for optimistic
 * concurrency.
 */
export type SaveLaunchProfileRequest =
  | ({ operation: 'create' } & CreateLaunchProfileRequest)
  | ({ operation: 'update' } & UpdateLaunchProfileRequest);
