// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SaveLaunchProfileRequest } from './SaveLaunchProfileRequest';
import type { SecretLaunchEnvironmentEntry } from './SecretLaunchEnvironmentEntry';

/**
 * Authenticated write request used to create or rotate system-backed
 * environment secrets. The nested profile request contains no new secret
 * values; entries here replace the matching environment slots before save.
 */
export type SaveLaunchProfileWithSecretsRequest = {
  request: SaveLaunchProfileRequest;
  secretEnvironment: Array<SecretLaunchEnvironmentEntry>;
};
