// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CreateClassificationRuleRequest } from './CreateClassificationRuleRequest';
import type { UpdateClassificationRuleRequest } from './UpdateClassificationRuleRequest';

export type SaveClassificationRuleRequest =
  | ({ operation: 'create' } & CreateClassificationRuleRequest)
  | ({ operation: 'update' } & UpdateClassificationRuleRequest);
