// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CreateProjectRequest } from './CreateProjectRequest';
import type { UpdateProjectRequest } from './UpdateProjectRequest';

export type SaveProjectRequest =
  | ({ operation: 'create' } & CreateProjectRequest)
  | ({ operation: 'update' } & UpdateProjectRequest);
