// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A write-only secret value supplied for one profile environment slot. It is
 * never persisted or returned by the Supervisor.
 */
export type SecretLaunchEnvironmentEntry = { name: string; secret: string };
