// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ShellKind } from './ShellKind';

export type ShellExecutionPreview = {
  shell: ShellKind;
  executable: string | null;
  argv: Array<string>;
  command: string;
};
