// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A shell is never inferred from command text. Selecting this enum is the
 * explicit opt-in required for shell execution.
 */
export type ShellKind = 'powerShell' | 'cmd' | 'zsh';
