// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Starts exactly the persisted profile revision named by the client. The
 * Supervisor owns executable resolution, the final environment, and all run
 * identity fields; none of those values are accepted on this request.
 */
export type StartManagedRunRequest = { profileId: string; expectedProfileUpdatedAt: string };
