// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Fixed action reserved for one batch member. A graceful reservation for a
 * launching run remains blocked until replay observes it as Running. `None`
 * is reserved for retained controls that cannot safely receive a new signal.
 */
export type StopAllForExitMemberAction =
  | { kind: 'none' }
  | { kind: 'gracefulRequested'; operationId: string }
  | { kind: 'stopAdopted'; operationId: string };
