// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExternalProcessStopOutcome } from './ExternalProcessStopOutcome';
import type { ExternalProcessStopScope } from './ExternalProcessStopScope';
import type { ProcessInstanceKey } from './ProcessInstanceKey';

export type StopExternalProcessResult = {
  processInstanceKey: ProcessInstanceKey;
  scope: ExternalProcessStopScope;
  outcome: ExternalProcessStopOutcome;
};
