// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StopExternalProcessConfirmation } from './StopExternalProcessConfirmation';

/**
 * Requests a conservative stop of one external process. Managed runs use
 * their separate run.stop and run.force_stop contracts.
 */
export type StopExternalProcessRequest = { confirmation: StopExternalProcessConfirmation };
