// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExternalProcessStopScope } from './ExternalProcessStopScope';
import type { ProcessInstanceKey } from './ProcessInstanceKey';

/**
 * Explicit user confirmation for one exact external process instance. The
 * identity is captured again here so a confirmation cannot be reused for a
 * different PID instance or widened to a process tree.
 */
export type StopExternalProcessConfirmation = {
  processInstanceKey: ProcessInstanceKey;
  scope: ExternalProcessStopScope;
};
