// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StopAllForExitMemberResult } from './StopAllForExitMemberResult';
import type { StopAllForExitStatus } from './StopAllForExitStatus';

export type StopAllForExitResult = {
  operationId: string;
  status: StopAllForExitStatus;
  members: Array<StopAllForExitMemberResult>;
};
