// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExitRunImpact } from './ExitRunImpact';
import type { StopAllForExitMemberAction } from './StopAllForExitMemberAction';

export type StopAllForExitMemberResult = {
  runId: string;
  action: StopAllForExitMemberAction;
  /**
   * Absent only after this fixed member no longer has any exit impact.
   */
  currentImpact: ExitRunImpact | null;
};
