// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Requests a graceful stop for a Supervisor-owned managed run. The
 * idempotency key is carried only by the authenticated request envelope.
 */
export type StopManagedRunRequest = { runId: string };
