// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Requests graceful stops for exactly the members in one prior assessment.
 * The idempotency key remains exclusively in the authenticated envelope.
 */
export type StopAllForExitRequest = { expectedAssessmentId: string };
