// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PortBinding } from './PortBinding';
import type { ProcessRecord } from './ProcessRecord';

export type SystemSnapshot = {
  /**
   * Identifies the frozen server-side view shared by every chunk.
   */
  snapshotId: string;
  chunkIndex: number;
  revision: number;
  processCount: number;
  portBindingCount: number;
  totalEntityBytes: number;
  processes: Array<ProcessRecord>;
  portBindings: Array<PortBinding>;
  nextCursor: string | null;
};
