// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EnvironmentLayer } from './EnvironmentLayer';
import type { PathUnknownReason } from './PathUnknownReason';

export type UnknownPathResolution = { reason: PathUnknownReason; source: EnvironmentLayer | null };
