// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClassificationRuleInput } from './ClassificationRuleInput';

export type UpdateClassificationRuleRequest = {
  ruleId: string;
  expectedUpdatedAt: string;
  input: ClassificationRuleInput;
};
