// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LaunchProfileInput } from './LaunchProfileInput';

export type UpdateLaunchProfileRequest = {
  profileId: string;
  expectedUpdatedAt: string;
  input: LaunchProfileInput;
};
