import { useId, type ReactNode } from 'react';
import {
  Binary,
  CircleCheck,
  CircleHelp,
  CircleOff,
  LoaderCircle,
  ShieldCheck,
  Terminal,
  TriangleAlert,
  type LucideIcon,
} from 'lucide-react';

import type {
  EnvironmentLayer,
  EnvironmentPreviewEntry,
  ExecutableCandidate,
  FinalExecutionPreview,
  ShellKind,
} from '@dpm/generated-types';

import { isSensitiveEnvironmentName } from './launchProfileModel';

const REDACTED_VALUE = '********';

const ENVIRONMENT_LAYERS: ReadonlyArray<{
  label: string;
  value: EnvironmentLayer;
}> = [
  { label: 'Supervisor base', value: 'supervisorBase' },
  { label: 'User', value: 'user' },
  { label: 'Project', value: 'project' },
  { label: 'Profile', value: 'profile' },
];

export type ExecutionPreviewEmptyState = 'noSelection' | 'invalidDraft' | 'notRequested';

export interface ExecutionPreviewPanelProps {
  emptyState?: ExecutionPreviewEmptyState;
  error: string | null;
  loading: boolean;
  pendingSecretNames: ReadonlyArray<string>;
  preview: FinalExecutionPreview | null;
  stale: boolean;
}

export function ExecutionPreviewPanel({
  emptyState = 'notRequested',
  error,
  loading,
  pendingSecretNames,
  preview,
  stale,
}: ExecutionPreviewPanelProps) {
  const titleId = useId();
  const pendingSecrets = deduplicateNames(pendingSecretNames);

  return (
    <aside
      aria-busy={loading}
      aria-labelledby={titleId}
      className="launch-preview-panel"
      data-stale={stale || undefined}
    >
      <header className="launch-preview-header">
        <div className="launch-preview-heading">
          <Terminal aria-hidden="true" size={18} strokeWidth={1.8} />
          <div>
            <h2 id={titleId}>Final execution preview</h2>
            <p>Generated by Supervisor from the current profile and host execution context.</p>
          </div>
        </div>
        <PreviewStatus error={error} loading={loading} preview={preview} stale={stale} />
      </header>

      <div aria-live="polite" className="launch-preview-announcements">
        {error ? (
          <PreviewNotice Icon={TriangleAlert} tone="danger" title="Supervisor preview failed">
            {error}
          </PreviewNotice>
        ) : null}
        {stale && preview ? (
          <PreviewNotice Icon={TriangleAlert} tone="warning" title="Preview is out of date">
            The draft has changed. Values below are from the previous Supervisor result.
          </PreviewNotice>
        ) : null}
        {pendingSecrets.length > 0 ? <PendingSecrets names={pendingSecrets} /> : null}
      </div>

      {preview ? (
        <PreviewContent preview={preview} />
      ) : (
        <EmptyPreview error={error} loading={loading} state={emptyState} />
      )}
    </aside>
  );
}

function PreviewStatus({
  error,
  loading,
  preview,
  stale,
}: Pick<ExecutionPreviewPanelProps, 'error' | 'loading' | 'preview' | 'stale'>) {
  let Icon: LucideIcon = ShieldCheck;
  let label = 'Supervisor result';
  let tone = 'ready';

  if (loading) {
    Icon = LoaderCircle;
    label = preview ? 'Refreshing with Supervisor' : 'Waiting for Supervisor';
    tone = 'busy';
  } else if (error) {
    Icon = TriangleAlert;
    label = preview ? 'Previous Supervisor result' : 'Preview unavailable';
    tone = 'danger';
  } else if (stale) {
    Icon = TriangleAlert;
    label = preview ? 'Previous Supervisor result' : 'Draft changed';
    tone = 'warning';
  } else if (!preview) {
    Icon = CircleHelp;
    label = 'No Supervisor result';
    tone = 'muted';
  }

  return (
    <span className="launch-preview-status" data-tone={tone}>
      <Icon
        aria-hidden="true"
        className={loading ? 'launch-preview-spin' : undefined}
        size={14}
        strokeWidth={1.8}
      />
      <span>{label}</span>
    </span>
  );
}

function PendingSecrets({ names }: { names: ReadonlyArray<string> }) {
  return (
    <section className="launch-preview-notice" data-tone="warning">
      <div className="launch-preview-notice-heading">
        <ShieldCheck aria-hidden="true" size={15} strokeWidth={1.8} />
        <h3>Pending secret values</h3>
      </div>
      <p>
        These values are masked and excluded from this preview. Save the profile before Supervisor
        can resolve them.
      </p>
      <dl className="launch-preview-pending-secrets">
        {names.map((name) => (
          <div key={name.toUpperCase()}>
            <dt className="launch-preview-mono launch-preview-breakable">{name}</dt>
            <dd aria-label="Redacted pending secret" className="launch-preview-redacted">
              {REDACTED_VALUE}
            </dd>
          </div>
        ))}
      </dl>
    </section>
  );
}

function PreviewNotice({
  Icon,
  children,
  title,
  tone,
}: {
  Icon: LucideIcon;
  children: ReactNode;
  title: string;
  tone: 'danger' | 'warning';
}) {
  return (
    <div
      className="launch-preview-notice"
      data-tone={tone}
      role={tone === 'danger' ? 'alert' : 'status'}
    >
      <div className="launch-preview-notice-heading">
        <Icon aria-hidden="true" size={15} strokeWidth={1.8} />
        <strong>{title}</strong>
      </div>
      <p>{children}</p>
    </div>
  );
}

function EmptyPreview({
  error,
  loading,
  state,
}: {
  error: string | null;
  loading: boolean;
  state: ExecutionPreviewEmptyState;
}) {
  if (loading) {
    return (
      <PreviewEmptyState
        Icon={LoaderCircle}
        detail="Supervisor is resolving the current draft against the host execution context."
        spinning
        title="Building final preview"
      />
    );
  }
  if (error) {
    return (
      <PreviewEmptyState
        Icon={TriangleAlert}
        detail="No prior Supervisor result is available for this draft."
        title="Final preview unavailable"
      />
    );
  }

  switch (state) {
    case 'noSelection':
      return (
        <PreviewEmptyState
          Icon={CircleHelp}
          detail="Choose a launch profile to inspect its resolved execution."
          title="No profile selected"
        />
      );
    case 'invalidDraft':
      return (
        <PreviewEmptyState
          Icon={TriangleAlert}
          detail="Resolve the highlighted profile fields before requesting a Supervisor preview."
          title="Draft cannot be previewed"
        />
      );
    case 'notRequested':
      return (
        <PreviewEmptyState
          Icon={CircleHelp}
          detail="A final preview will appear after Supervisor resolves a valid draft."
          title="No final preview yet"
        />
      );
  }
}

function PreviewEmptyState({
  Icon,
  detail,
  spinning = false,
  title,
}: {
  Icon: LucideIcon;
  detail: string;
  spinning?: boolean;
  title: string;
}) {
  return (
    <div className="launch-preview-empty">
      <Icon
        aria-hidden="true"
        className={spinning ? 'launch-preview-spin' : undefined}
        size={20}
        strokeWidth={1.7}
      />
      <strong>{title}</strong>
      <p>{detail}</p>
    </div>
  );
}

function PreviewContent({ preview }: { preview: FinalExecutionPreview }) {
  return (
    <div className="launch-preview-content">
      <PreviewSection Icon={CircleCheck} title="Execution context">
        <dl className="launch-preview-fields">
          <PreviewField label="Platform">{platformLabel(preview.platform)}</PreviewField>
          <PreviewField label="Working directory" mono>
            {preview.workingDirectory}
          </PreviewField>
          <PreviewField label="Interactive">
            {preview.interactive ? 'Enabled' : 'Disabled'}
          </PreviewField>
          <PreviewField label="Credential resolution">
            {preview.requiresCredentialResolution
              ? 'Required before launch'
              : 'No unresolved credentials'}
          </PreviewField>
        </dl>
      </PreviewSection>

      <InvocationPreview preview={preview} />
      <PathPreview preview={preview} />
      <ExecutableResolutionPreview preview={preview} />
      <EnvironmentPreview entries={preview.environment} />
    </div>
  );
}

function InvocationPreview({ preview }: { preview: FinalExecutionPreview }) {
  const { invocation } = preview;
  return (
    <PreviewSection Icon={Terminal} title="Invocation">
      <dl className="launch-preview-fields">
        <PreviewField label="Mode">
          {invocation.mode === 'direct' ? 'Direct' : 'Shell'}
        </PreviewField>
        {invocation.mode === 'direct' ? (
          <PreviewField label="Executable" mono>
            {invocation.executable}
          </PreviewField>
        ) : (
          <>
            <PreviewField label="Shell">{shellLabel(invocation.shell)}</PreviewField>
            <PreviewField label="Shell executable" mono>
              {invocation.executable ?? 'Unavailable on selected platform'}
            </PreviewField>
            <PreviewField label="Command" mono preformatted>
              {invocation.command}
            </PreviewField>
          </>
        )}
      </dl>
      <ArgumentList arguments={invocation.argv} />
    </PreviewSection>
  );
}

function ArgumentList({ arguments: values }: { arguments: ReadonlyArray<string> }) {
  return (
    <div className="launch-preview-subsection">
      <h4>argv</h4>
      {values.length > 0 ? (
        <ol className="launch-preview-argv">
          {values.map((value, index) => (
            <li key={`${index}:${value}`}>
              <span aria-hidden="true" className="launch-preview-index">
                {index}
              </span>
              <pre className="launch-preview-code">{value}</pre>
            </li>
          ))}
        </ol>
      ) : (
        <p className="launch-preview-muted">No arguments</p>
      )}
    </div>
  );
}

function PathPreview({ preview }: { preview: FinalExecutionPreview }) {
  return (
    <PreviewSection Icon={Binary} title="Path resolution">
      <div className="launch-preview-resolution-grid">
        <section className="launch-preview-resolution">
          <h4>PATH</h4>
          {preview.path.status === 'known' ? (
            <>
              <ResolutionStatus status="known" text="Known" />
              <ResolutionSource source={preview.path.source} />
              <pre className="launch-preview-code">{preview.path.value}</pre>
            </>
          ) : (
            <>
              <ResolutionStatus status="unknown" text="Unknown" />
              <ResolutionSource source={preview.path.source} />
              <p>{pathUnknownReasonLabel(preview.path.reason)}</p>
            </>
          )}
        </section>

        <section className="launch-preview-resolution">
          <h4>PATHEXT</h4>
          <PathExtensionPreview preview={preview} />
        </section>
      </div>
    </PreviewSection>
  );
}

function PathExtensionPreview({ preview }: { preview: FinalExecutionPreview }) {
  const resolution = preview.pathExtensions;
  switch (resolution.status) {
    case 'known':
      return (
        <>
          <ResolutionStatus status="known" text="Known" />
          <ResolutionSource source={resolution.source} />
          <pre className="launch-preview-code">{resolution.value}</pre>
          {resolution.extensions.length > 0 ? (
            <ul className="launch-preview-token-list" aria-label="PATHEXT entries">
              {resolution.extensions.map((extension, index) => (
                <li className="launch-preview-mono" key={`${index}:${extension}`}>
                  {extension}
                </li>
              ))}
            </ul>
          ) : null}
        </>
      );
    case 'unknown':
      return (
        <>
          <ResolutionStatus status="unknown" text="Unknown" />
          <ResolutionSource source={resolution.source} />
          <p>{pathUnknownReasonLabel(resolution.reason)}</p>
        </>
      );
    case 'notApplicable':
      return (
        <>
          <ResolutionStatus status="notApplicable" text="Not applicable" />
          <p>PATHEXT is not used on this platform.</p>
        </>
      );
  }
}

function ExecutableResolutionPreview({ preview }: { preview: FinalExecutionPreview }) {
  const resolution = preview.executableResolution;
  const status = resolution.status;
  return (
    <PreviewSection
      Icon={status === 'notSupported' ? CircleOff : CircleHelp}
      title="Executable resolution"
    >
      <div className="launch-preview-resolution launch-preview-resolution--wide">
        <ResolutionStatus
          status={status}
          text={
            status === 'notFound'
              ? 'Not found'
              : status === 'notSupported'
                ? 'Not supported'
                : 'Unknown'
          }
        />
        <p>{executableReasonLabel(resolution)}</p>
        {'candidates' in resolution ? (
          <ExecutableCandidates candidates={resolution.candidates} />
        ) : null}
      </div>
    </PreviewSection>
  );
}

function ExecutableCandidates({ candidates }: { candidates: ReadonlyArray<ExecutableCandidate> }) {
  return (
    <div className="launch-preview-subsection">
      <h4>Candidate paths</h4>
      {candidates.length > 0 ? (
        <ol className="launch-preview-candidates">
          {candidates.map((candidate, index) => (
            <li key={`${index}:${candidate.path}`}>
              <pre className="launch-preview-code">{candidate.path}</pre>
              <small>{candidateSourceLabel(candidate)}</small>
            </li>
          ))}
        </ol>
      ) : (
        <p className="launch-preview-muted">No candidate paths</p>
      )}
    </div>
  );
}

function EnvironmentPreview({ entries }: { entries: ReadonlyArray<EnvironmentPreviewEntry> }) {
  return (
    <PreviewSection Icon={ShieldCheck} title="Environment by source">
      {entries.length > 0 ? (
        <div className="launch-preview-environment-groups">
          {ENVIRONMENT_LAYERS.map((layer) => {
            const sourceEntries = entries.filter((entry) => entry.source === layer.value);
            if (sourceEntries.length === 0) {
              return null;
            }
            return (
              <section className="launch-preview-environment-group" key={layer.value}>
                <h4>{layer.label}</h4>
                <dl className="launch-preview-environment-list">
                  {sourceEntries.map((entry, index) => (
                    <EnvironmentValue entry={entry} key={`${entry.name}:${index}`} />
                  ))}
                </dl>
              </section>
            );
          })}
        </div>
      ) : (
        <p className="launch-preview-muted">No environment entries</p>
      )}
    </PreviewSection>
  );
}

function EnvironmentValue({ entry }: { entry: EnvironmentPreviewEntry }) {
  const presentation = environmentValuePresentation(entry);
  return (
    <div
      className="launch-preview-environment-row"
      data-redacted={presentation.redacted || undefined}
    >
      <dt className="launch-preview-mono launch-preview-breakable">{entry.name}</dt>
      <dd>
        <pre
          aria-label={presentation.redacted ? `Redacted value for ${entry.name}` : undefined}
          className={
            presentation.redacted
              ? 'launch-preview-code launch-preview-redacted'
              : 'launch-preview-code'
          }
        >
          {presentation.value}
        </pre>
        {presentation.detail ? <small>{presentation.detail}</small> : null}
      </dd>
    </div>
  );
}

function PreviewSection({
  Icon,
  children,
  title,
}: {
  Icon: LucideIcon;
  children: ReactNode;
  title: string;
}) {
  const headingId = useId();
  return (
    <section aria-labelledby={headingId} className="launch-preview-section">
      <h3 id={headingId}>
        <Icon aria-hidden="true" size={15} strokeWidth={1.8} />
        <span>{title}</span>
      </h3>
      {children}
    </section>
  );
}

function PreviewField({
  children,
  label,
  mono = false,
  preformatted = false,
}: {
  children: ReactNode;
  label: string;
  mono?: boolean;
  preformatted?: boolean;
}) {
  return (
    <div>
      <dt>{label}</dt>
      <dd className={mono ? 'launch-preview-mono launch-preview-breakable' : undefined}>
        {preformatted ? <pre className="launch-preview-code">{children}</pre> : children}
      </dd>
    </div>
  );
}

function ResolutionStatus({
  status,
  text,
}: {
  status: 'known' | 'notApplicable' | 'notFound' | 'notSupported' | 'unknown';
  text: string;
}) {
  const Icon =
    status === 'known' ? CircleCheck : status === 'notSupported' ? CircleOff : CircleHelp;
  return (
    <span className="launch-preview-resolution-status" data-status={status}>
      <Icon aria-hidden="true" size={14} strokeWidth={1.8} />
      <span>{text}</span>
    </span>
  );
}

function ResolutionSource({ source }: { source: EnvironmentLayer | null }) {
  return (
    <small className="launch-preview-resolution-source">
      Source: {source === null ? 'Unavailable' : environmentLayerLabel(source)}
    </small>
  );
}

function environmentValuePresentation(entry: EnvironmentPreviewEntry): {
  detail: string | null;
  redacted: boolean;
  value: string;
} {
  if (isSensitiveEnvironmentName(entry.name)) {
    return {
      detail: 'Sensitive variable name; value masked by the desktop.',
      redacted: true,
      value: REDACTED_VALUE,
    };
  }
  if (entry.value === 'credentialReferenceRedacted') {
    return {
      detail: 'Credential-backed value redacted by Supervisor.',
      redacted: true,
      value: REDACTED_VALUE,
    };
  }
  if (entry.value === 'inheritedRedacted') {
    return {
      detail: 'Inherited value redacted by Supervisor.',
      redacted: true,
      value: REDACTED_VALUE,
    };
  }
  return { detail: null, redacted: false, value: entry.value.plain };
}

function executableReasonLabel(resolution: FinalExecutionPreview['executableResolution']): string {
  switch (resolution.status) {
    case 'unknown':
      switch (resolution.reason) {
        case 'filesystemNotInspected':
          return 'Candidate paths were computed, but the filesystem was not inspected.';
        case 'pathMissing':
          return 'PATH is missing, so the executable cannot be resolved.';
        case 'pathInvalidValue':
          return 'PATH is invalid, so the executable cannot be resolved.';
        case 'pathCredentialReference':
          return 'PATH depends on a credential-backed value that is not resolved in previews.';
        case 'pathExtensionMissing':
          return 'PATHEXT is missing, so the Windows executable cannot be resolved.';
        case 'pathExtensionCredentialReference':
          return 'PATHEXT depends on a credential-backed value that is not resolved in previews.';
      }
    case 'notFound':
      return 'The executable search path is empty.';
    case 'notSupported':
      return resolution.reason === 'shellUnavailableOnPlatform'
        ? 'The selected shell is unavailable on this platform.'
        : 'The executable path is invalid for this platform.';
  }
}

function pathUnknownReasonLabel(reason: 'credentialReference' | 'invalidValue' | 'missing') {
  switch (reason) {
    case 'credentialReference':
      return 'The value depends on a credential reference and is not resolved in previews.';
    case 'invalidValue':
      return 'The value cannot be parsed as a valid search path.';
    case 'missing':
      return 'No value is present in the merged environment.';
  }
}

function candidateSourceLabel(candidate: ExecutableCandidate) {
  const { source } = candidate;
  if (source === 'explicit') {
    return 'Explicit executable path';
  }
  if (source === 'workingDirectory') {
    return 'Working directory';
  }
  return `${environmentLayerLabel(source.path.pathSource)} PATH entry ${source.path.pathIndex} / ${pathEntryKindLabel(source.path.entryKind)}`;
}

function pathEntryKindLabel(
  kind: 'absolute' | 'workingDirectoryEmpty' | 'workingDirectoryRelative',
) {
  switch (kind) {
    case 'absolute':
      return 'absolute';
    case 'workingDirectoryEmpty':
      return 'empty entry resolved from working directory';
    case 'workingDirectoryRelative':
      return 'relative entry resolved from working directory';
  }
}

function environmentLayerLabel(layer: EnvironmentLayer) {
  switch (layer) {
    case 'supervisorBase':
      return 'Supervisor base';
    case 'user':
      return 'User';
    case 'project':
      return 'Project';
    case 'profile':
      return 'Profile';
  }
}

function platformLabel(platform: FinalExecutionPreview['platform']) {
  return platform === 'windows' ? 'Windows' : 'macOS';
}

function shellLabel(shell: ShellKind) {
  switch (shell) {
    case 'powerShell':
      return 'PowerShell';
    case 'cmd':
      return 'Command Prompt';
    case 'zsh':
      return 'Z shell';
  }
}

function deduplicateNames(names: ReadonlyArray<string>) {
  const seen = new Set<string>();
  return names.filter((name) => {
    const key = name.toUpperCase();
    if (seen.has(key)) {
      return false;
    }
    seen.add(key);
    return true;
  });
}
